#!/bin/bash

# Remote server details (modify these)
HOST="3040d50bb61e.f861a72c.alx-cod.online"
USERNAME="3040d50bb61e"
SSH_KEY="$HOME/.ssh/id_rsa"  # Path to your SSH private key

# Check if file argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 PATH_TO_FILE"
    exit 1
fi

PATH_TO_FILE="$1"

# Transfer file using SCP (disable strict host checking)
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$HOST":~/

echo "File transferred successfully to $USERNAME@$HOST:~/"