#!/usr/bin/env bash
# Sets up a 301 redirect on /redirect_me using Nginx

# Exit immediately if a command exits with a non-zero status
set -e

# Install nginx if not already installed
apt-get update
apt-get install -y nginx

# Create the directory for the redirect page
mkdir -p /var/www/html/redirect_me

# Configure Nginx to redirect /redirect_me
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
